resilience4j:
  circuitbreaker:
    instances:
      asyncClient:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
  retry:
    instances:
      asyncClient:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      asyncClient:
        timeoutDuration: 30s





logging:
  level:
    org:
      springframework:
        web=DEBUG:
        web:
          reactive:
            function:
              client=DEBUG:
    com:
      example:
        webclient=DEBUG:

